image: $CI_REGISTRY/vlasami6/fmltest:master

test:
  script:
    - meson setup build
    - meson compile -C build
    #- cppcheck --error-exitcode=1 *.c
    - env FML="$(readlink -f ./build/fml)" FML_REF=/cfml/fml /FMLtest/suite bc_interpret
        hello_world
        escape
        push_pop
        locals
        globals
        condition
        loop
        function0
        function1
        function_with_locals
        function_with_globals
        recursive_function
        aliasing
        object
        methods
        operators
        dispatch
        arrays
        getters_and_setters
        